graph TB
  linkStyle default fill:#ffffff

  subgraph diagram ["flarelette-hono - Containers"]
    style diagram fill:#ffffff,stroke:#ffffff

    subgraph 1 ["flarelette-hono"]
      style 1 fill:#ffffff,stroke:#0b4884,color:#0b4884

      2("<div style='font-weight: bold'>@chrislyons-dev/flarelette-hono</div><div style='font-size: 70%; margin-top: 0px'>[Container: Service]</div><div style='font-size: 80%; margin-top:10px'>Type-safe JWT authentication<br />middleware for Hono on<br />Cloudflare Workers</div>")
      style 2 fill:#438dd5,stroke:#2e6295,color:#ffffff
      35("<div style='font-weight: bold'>flarelette-hono-authenticated-example</div><div style='font-size: 70%; margin-top: 0px'>[Container: Service]</div><div style='font-size: 80%; margin-top:10px'>Service:<br />flarelette-hono-authenticated-example</div>")
      style 35 fill:#438dd5,stroke:#2e6295,color:#ffffff
      36("<div style='font-weight: bold'>flarelette-hono-minimal-example</div><div style='font-size: 70%; margin-top: 0px'>[Container: Service]</div><div style='font-size: 80%; margin-top:10px'>Service:<br />flarelette-hono-minimal-example</div>")
      style 36 fill:#438dd5,stroke:#2e6295,color:#ffffff
    end

  end