graph TB
  linkStyle default fill:#ffffff

  subgraph diagram ["flarelette-hono - @chrislyons-dev/flarelette-hono - Components"]
    style diagram fill:#ffffff,stroke:#ffffff

    subgraph 2 ["@chrislyons-dev/flarelette-hono"]
      style 2 fill:#ffffff,stroke:#2e6295,color:#2e6295

      10("<div style='font-weight: bold'>middleware.authGuard</div><div style='font-size: 70%; margin-top: 0px'>[Component: function]</div><div style='font-size: 80%; margin-top:10px'>Authentication guard<br />middleware Verifies JWT<br />tokens and optionally<br />enforces authorization<br />policies. Injects verified<br />payload into context as<br />`auth` variable.</div>")
      style 10 fill:#85bbf0,stroke:#5d82a8,color:#000000
      9("<div style='font-weight: bold'>middleware.extractBearerToken</div><div style='font-size: 70%; margin-top: 0px'>[Component: function]</div><div style='font-size: 80%; margin-top:10px'>Extract Bearer token from<br />Authorization header</div>")
      style 9 fill:#85bbf0,stroke:#5d82a8,color:#000000
    end

  end