@startuml
set separator none
title flarelette-hono - @chrislyons-dev/flarelette-hono - Components

top to bottom direction
skinparam ranksep 60
skinparam nodesep 30

skinparam {
  arrowFontSize 10
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 100
  defaultFontName "Arial"
}

hide stereotype

skinparam rectangle<<flarelettehono.chrislyonsdevflarelettehono.middlewareauthGuard>> {
  BackgroundColor #85bbf0
  FontColor #000000
  BorderColor #5d82a8
  roundCorner 20
  shadowing false
}
skinparam rectangle<<flarelettehono.chrislyonsdevflarelettehono.middlewareextractBearerToken>> {
  BackgroundColor #85bbf0
  FontColor #000000
  BorderColor #5d82a8
  roundCorner 20
  shadowing false
}
skinparam rectangle<<flarelettehono.chrislyonsdevflarelettehono>> {
  BorderColor #2e6295
  FontColor #2e6295
  shadowing false
}

rectangle "@chrislyons-dev/flarelette-hono\n<size:10>[Container: Service]</size>" <<flarelettehono.chrislyonsdevflarelettehono>> {
  rectangle "==middleware.authGuard\n<size:10>[Component: function]</size>\n\nAuthentication guard middleware Verifies JWT tokens and optionally enforces authorization policies. Injects verified payload into context as `auth` variable." <<flarelettehono.chrislyonsdevflarelettehono.middlewareauthGuard>> as flarelettehono.chrislyonsdevflarelettehono.middlewareauthGuard
  rectangle "==middleware.extractBearerToken\n<size:10>[Component: function]</size>\n\nExtract Bearer token from Authorization header" <<flarelettehono.chrislyonsdevflarelettehono.middlewareextractBearerToken>> as flarelettehono.chrislyonsdevflarelettehono.middlewareextractBearerToken
}

@enduml